# <job: test>
- exp_name: ant_d8_s2000
  env_id: ant
  depth: 8
  seed: 2000
  num_epochs: 100
  total_env_steps: 100000000
  actor_network_width: 256
  critic_network_width: 256
  batch_size: 512
  num_envs: 512
  actor_lr: 0.0003
  critic_lr: 0.0003
  alpha_lr: 0.0003
  unroll_length: 62
  max_replay_size: 10000
  min_replay_size: 1000
  entropy_param: 0.5
  gamma: 0.99
  logsumexp_penalty_coeff: 0.1
  disable_entropy: 0
  use_relu: 0
  num_episodes_per_env: 1
  training_steps_multiplier: 1
  use_all_batches: 0
  num_sgd_batches_per_training_step: 800
  eval_actor: 0
  expl_actor: 1
  num_eval_envs: 128
  episode_length: 1000
  resume_from: auto
  checkpoint: true
  checkpoint_save_interval_epochs: 10
  checkpoint_max_to_keep: 3
  checkpoint_keep_period: 50
  save_buffer: 0
  capture_vis: false
  num_render: 10
  track: true
  wandb_mode: online
  wandb_group: ''
  wandb_project_name: scaling-crl-nano4
  wandb_entity: sungwayne99999-national-cheng-kung-university-co-op
  wandb_dir: .
